#!/bin/bash

# Check if the script is run with root privileges
if [ "$EUID" -ne 0 ]; then
  echo "Please run this script as root or with sudo."
  exit 1
fi

# Update package lists
apt update -y

# Install OpenJDK 11
apt install openjdk-11-jre -y

# Install Docker
apt install docker.io -y

# Enable and start Docker service
systemctl enable docker
systemctl start docker

# Add the current user to the Docker group
CURRENT_USER=$(whoami)
usermod -aG docker $CURRENT_USER

# Get Jenkins initial admin password
until [ -f /var/lib/jenkins/secrets/initialAdminPassword ]; do
  sleep 5
done

JENKINS_INITIAL_PASSWORD=$(sudo cat /var/lib/jenkins/secrets/initialAdminPassword)

# Create Jenkins user
JENKINS_USER="your_jenkins_user"
JENKINS_PASSWORD="your_jenkins_password"

sudo useradd -m -s /bin/bash $JENKINS_USER

# Set Jenkins user password
echo "$JENKINS_USER:$JENKINS_PASSWORD" | sudo chpasswd

# Add Jenkins user to the Docker group
usermod -aG docker $JENKINS_USER

# Print the Jenkins initial admin password and Jenkins user details
echo "Jenkins Initial Admin Password: $JENKINS_INITIAL_PASSWORD"
echo "Jenkins User: $JENKINS_USER"
echo "Jenkins Password: $JENKINS_PASSWORD"
